<?php

namespace App\Enum;

enum Permissions: string
{
    // Users
    case VIEW_USERS = 'VIEW_USER';
    case CREATE_USERS = 'CREATE_USER';
    case UPDATE_USERS= 'UPDATE_USER';
    case DELETE_USERS = 'DELETE_USER';

    // Roles
    case VIEW_ROLES = 'VIEW_ROLE';
    case CREATE_ROLES = 'CREATE_ROLE';
    case UPDATE_ROLES = 'UPDATE_ROLE';
    case DELETE_ROLES = 'DELETE_ROLE';

    // Doctors
    case VIEW_DOCTORS = 'VIEW_DOCTOR';
    case CREATE_DOCTORS = 'CREATE_DOCTOR';
    case UPDATE_DOCTORS = 'UPDATE_DOCTOR';
    case DELETE_DOCTORS = 'DELETE_DOCTOR';

    // Diseases
    case VIEW_DISEASES = 'VIEW_DISEASE';
    case CREATE_DISEASES = 'CREATE_DISEASE';
    case UPDATE_DISEASES = 'UPDATE_DISEASE';
    case DELETE_DISEASES = 'DELETE_DISEASE';

    // Patients
    case VIEW_PATIENTS = 'VIEW_PATIENT';
    case CREATE_PATIENTS = 'CREATE_PATIENT';
    case UPDATE_PATIENTS = 'UPDATE_PATIENT';
    case DELETE_PATIENTS = 'DELETE_PATIENT';

    // Appointments
    case VIEW_APPOINTMENTS = 'VIEW_APPOINTMENT';
    case CREATE_APPOINTMENTS = 'CREATE_APPOINTMENT';
    case UPDATE_APPOINTMENTS = 'UPDATE_APPOINTMENT';
    case DELETE_APPOINTMENTS = 'DELETE_APPOINTMENT';

    // Consultations
    case VIEW_CONSULTATIONS = 'VIEW_CONSULTATION';
    case CREATE_CONSULTATIONS = 'CREATE_CONSULTATION';
    case UPDATE_CONSULTATIONS = 'UPDATE_CONSULTATION';
    case DELETE_CONSULTATIONS = 'DELETE_CONSULTATION';

    // Follow Ups
    case VIEW_FOLLOW_UPS = 'VIEW_FOLLOW_UP';
    case CREATE_FOLLOW_UPS = 'CREATE_FOLLOW_UP';
    case UPDATE_FOLLOW_UPS = 'UPDATE_FOLLOW_UP';
    case DELETE_FOLLOW_UPS = 'DELETE_FOLLOW_UP';

    // Lab Tests
    case VIEW_LAB_TESTS = 'VIEW_LAB_TEST';
    case CREATE_LAB_TESTS = 'CREATE_LAB_TEST';
    case UPDATE_LAB_TESTS = 'UPDATE_LAB_TEST';
    case DELETE_LAB_TESTS = 'DELETE_LAB_TEST';

    // Prescriptions
    case VIEW_PRESCRIPTIONS = 'VIEW_PRESCRIPTION';
    case CREATE_PRESCRIPTIONS = 'CREATE_PRESCRIPTION';
    case UPDATE_PRESCRIPTIONS = 'UPDATE_PRESCRIPTION';
    case DELETE_PRESCRIPTIONS = 'DELETE_PRESCRIPTION';

    // Payments
    case VIEW_PAYMENTS = 'VIEW_PAYMENT';
    case CREATE_PAYMENTS = 'CREATE_PAYMENT';
    case UPDATE_PAYMENTS = 'UPDATE_PAYMENT';
    case DELETE_PAYMENTS = 'DELETE_PAYMENT';

    // Stock Entries
    case VIEW_STOCK_ENTRIES = 'VIEW_STOCK_ENTRY';
    case CREATE_STOCK_ENTRIES = 'CREATE_STOCK_ENTRY';
    case UPDATE_STOCK_ENTRIES = 'UPDATE_STOCK_ENTRY';
    case DELETE_STOCK_ENTRIES = 'DELETE_STOCK_ENTRY';

    // Medicine Categories
    case VIEW_MEDICINE_CATEGORIES = 'VIEW_MEDICINE_CATEGORY';
    case CREATE_MEDICINE_CATEGORIES = 'CREATE_MEDICINE_CATEGORY';
    case UPDATE_MEDICINE_CATEGORIES = 'UPDATE_MEDICINE_CATEGORY';
    case DELETE_MEDICINE_CATEGORIES = 'DELETE_MEDICINE_CATEGORY';

    // Medicines
    case VIEW_MEDICINES = 'VIEW_MEDICINE';
    case CREATE_MEDICINES = 'CREATE_MEDICINE';
    case UPDATE_MEDICINES = 'UPDATE_MEDICINE';
    case DELETE_MEDICINES = 'DELETE_MEDICINE';

    // Medicine Variants
    case VIEW_MEDICINE_VARIANTS = 'VIEW_MEDICINE_VARIANT';
    case CREATE_MEDICINE_VARIANTS = 'CREATE_MEDICINE_VARIANT';
    case UPDATE_MEDICINE_VARIANTS = 'UPDATE_MEDICINE_VARIANT';
    case DELETE_MEDICINE_VARIANTS = 'DELETE_MEDICINE_VARIANT';

    // Medicine Forms
    case VIEW_MEDICINE_FORMS = 'VIEW_MEDICINE_FORM';
    case CREATE_MEDICINE_FORMS = 'CREATE_MEDICINE_FORM';
    case UPDATE_MEDICINE_FORMS = 'UPDATE_MEDICINE_FORM';
    case DELETE_MEDICINE_FORMS = 'DELETE_MEDICINE_FORM';

    // Life Styles
    case VIEW_LIFE_STYLES = 'VIEW_LIFE_STYLE';
    case CREATE_LIFE_STYLES = 'CREATE_LIFE_STYLE';
    case UPDATE_LIFE_STYLES = 'UPDATE_LIFE_STYLE';
    case DELETE_LIFE_STYLES = 'DELETE_LIFE_STYLE';


}

